BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `partida` (
	`perdedor_id`	INTEGER NOT NULL,
	`ganhador_id`	INTEGER NOT NULL,
	`total_cash`	INTEGER NOT NULL,
	FOREIGN KEY(`ganhador_id`) REFERENCES `jogador`(`id`),
	FOREIGN KEY(`perdedor_id`) REFERENCES `jogador`(`id`)
);
CREATE TABLE IF NOT EXISTS `jogador` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`nickname`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`cash`	INTEGER NOT NULL DEFAULT 10000
);
COMMIT;
